language: python
python:
    - "3.5"
    - "3.6"
    - "nightly"

install: 
    - "pip install -r requirements.txt"
    - "pip install codecov"

script: 
    - export PYTHONPATH=`pwd`
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=silica test;else pytest --cov=silica test; fi

after_success:
    - codecov
