language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get -qq update

install: 
    - sudo apt-get install verilator
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"
    - "pip install -e git+ssh://git@github.com/phanrahan/magmacore@feature/circuit-port-repr#egg=magma"
    - "pip install -e git+ssh://git@github.com/phanrahan/mantle@feature/expression-support-for-silica#egg=mantle"
    - "pip install -e git+ssh://git@github.com/phanrahan/loam#egg=loam"
    - "pip install codecov"

script: 
    - export PYTHONPATH=`pwd`
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=silica test;else pytest --cov=silica test; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
