language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get -qq update

install: 
    - sudo apt-get install verilator
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"
    - "pip install -e magma"
    - "pip install -e mantle"
    - "pip install -e loam"
    - "pip install codecov"

script: 
    - pip install -e .
    - export MANTLE=lattice
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=silica test;else pytest --cov=silica test; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
