language: python
python:
    - "3.5"
    - "3.6"
    - "nightly"

install: 
    - "pip install -r requirements.txt"

script: 
    - export PYTHONPATH=`pwd`
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=silica --cov-report term-missing test;else pytest --cov=silica --cov-report term-missing test; fi
    - codecov
